export const agentNodes = [
  {
    id: 'planner',
    label: 'Planner Agent',
    role: 'Breaks task into subtasks',
    trustScore: 0.82,
    score: 0.86,
    costUsd: 0.018,
    latencySeconds: 4.2,
    tokens: 1420,
    passedTasks: 1,
    failedTasks: 0,
    status: 'passed',
    weakLink: false,
    lastInput: 'software_dev_bugfix_001 task description',
    lastOutput: 'Plan with divide-by-zero guard and unit-test suggestion',
  },
  {
    id: 'researcher',
    label: 'Research Agent',
    role: 'Collects evidence and sources',
    trustScore: 0.76,
    score: 0.74,
    costUsd: 0.022,
    latencySeconds: 6.8,
    tokens: 1880,
    passedTasks: 1,
    failedTasks: 0,
    status: 'passed',
    weakLink: false,
    lastInput: 'planner assumptions and required constraints',
    lastOutput: 'Evidence packet with Python exception-handling guidance',
  },
  {
    id: 'coder',
    label: 'Coder Agent',
    role: 'Implements solution',
    trustScore: 0.61,
    score: 0.52,
    costUsd: 0.071,
    latencySeconds: 39.1,
    tokens: 5120,
    passedTasks: 0,
    failedTasks: 1,
    status: 'warning',
    weakLink: true,
    lastInput: 'evidence + implementation constraints + test failure',
    lastOutput: 'Patch attempted but failed one unit test after 3 retries',
  },
  {
    id: 'reviewer',
    label: 'Reviewer Agent',
    role: 'Checks correctness and risk',
    trustScore: 0.88,
    score: 0.89,
    costUsd: 0.027,
    latencySeconds: 8.3,
    tokens: 2310,
    passedTasks: 1,
    failedTasks: 0,
    status: 'passed',
    weakLink: false,
    lastInput: 'patch + rationale from coder',
    lastOutput: 'Security issue found, requested revision',
  },
  {
    id: 'executor',
    label: 'Execution Agent',
    role: 'Runs tests and tools',
    trustScore: 0.93,
    score: 0.94,
    costUsd: 0.009,
    latencySeconds: 12.4,
    tokens: 740,
    passedTasks: 1,
    failedTasks: 0,
    status: 'passed',
    weakLink: false,
    lastInput: 'test plan + code patch',
    lastOutput: 'Unit test failed: divide_by_zero_returns_none',
  },
];

export const handoffs = [
  {
    id: 'handoff-planner-researcher',
    source: 'planner',
    target: 'researcher',
    label: 'research plan + assumptions',
    score: 0.84,
  },
  {
    id: 'handoff-researcher-coder',
    source: 'researcher',
    target: 'coder',
    label: 'evidence + implementation constraints',
    score: 0.71,
  },
  {
    id: 'handoff-coder-reviewer',
    source: 'coder',
    target: 'reviewer',
    label: 'patch + rationale',
    score: 0.58,
  },
  {
    id: 'handoff-reviewer-executor',
    source: 'reviewer',
    target: 'executor',
    label: 'test plan + risk notes',
    score: 0.91,
  },
];

export const loops = [
  {
    id: 'loop-reviewer-coder',
    source: 'reviewer',
    target: 'coder',
    label: 'revision loop: security issue found',
    iterations: 2,
    costUsd: 0.042,
    latencySeconds: 18.4,
    improvedScore: true,
  },
  {
    id: 'loop-executor-coder',
    source: 'executor',
    target: 'coder',
    label: 'test-fix loop: failing unit test',
    iterations: 3,
    costUsd: 0.061,
    latencySeconds: 31.7,
    improvedScore: false,
  },
];

export const taskScores = [
  { taskId: 'software_dev_bugfix_001', agent: 'planner', score: 0.86, passed: true },
  { taskId: 'software_dev_bugfix_001', agent: 'researcher', score: 0.74, passed: true },
  { taskId: 'software_dev_bugfix_001', agent: 'coder', score: 0.52, passed: false },
  { taskId: 'software_dev_bugfix_001', agent: 'reviewer', score: 0.89, passed: true },
  { taskId: 'software_dev_bugfix_001', agent: 'executor', score: 0.94, passed: true },
];

export const executionLogs = [
  {
    id: 'log-1',
    time: '00:00:01',
    type: 'agent',
    targetId: 'planner',
    message: 'Planner created implementation plan',
    score: 0.86,
  },
  {
    id: 'log-2',
    time: '00:00:07',
    type: 'handoff',
    targetId: 'handoff-researcher-coder',
    message: 'Researcher passed constraints to coder',
    score: 0.71,
  },
  {
    id: 'log-3',
    time: '00:00:16',
    type: 'loop',
    targetId: 'loop-reviewer-coder',
    message: 'Reviewer sent patch back due to security issue',
    score: 0.66,
  },
  {
    id: 'log-4',
    time: '00:00:39',
    type: 'loop',
    targetId: 'loop-executor-coder',
    message: 'Executor found failing unit test after retry loop',
    score: 0.52,
  },
  {
    id: 'log-5',
    time: '00:00:43',
    type: 'agent',
    targetId: 'coder',
    message: 'Coder identified as weak link',
    score: 0.52,
  },
];
